name1 = input("enter name of the first person : ")
name2 = input("enter name of the second person : ")
name3 = input("enter name of the third person : ")
name4 = input("enter name of the fourth person : ")
name5 = input("enter name of the fifth person : ")

age1 = input("enter age of first person : ")
age2 = input("enter age of second person : ")
age3 = input("enter age of third person : ")
age4 = input("enter age of fourth person : ")
age5 = input("enter age of fifth person : ")

gender1 = input("enter gender of first person : ")
gender2 = input("enter gender of second person : ")
gender3 = input("enter gender of third person : ")
gender4 = input("enter gender of fourth person : ")
gender5 = input("enter gender of fifth person : ")

contact1 = input("enter contact number of first person : ")
contact2 = input("enter contact number of second person : ")
contact3 = input("enter contact number of third person : ")
contact4 = input("enter contact number of fourth person : ")
contact5 = input("enter contact number of fifth person : ")
print()
print()
print("NAME" ,   "AGE" ,   "GENDER" ,   "CONTACT NUMBER")
print(name1 , age1 , gender1 , contact1)
print()
print(name2 , age2 , gender2 , contact2)
print()
print(name3 , age3 , gender3 , contact3)
print()
print(name4 , age4 , gender4 , contact4)
print()
print(name5 , age5 , gender5 , contact5)
